<?php

trait ConvertM1M2_Mapping
{
    protected function _getReplaceMaps()
    {
        return [
            'modules' => [
                'Mage_Adminhtml' => 'Magento_Backend',
            ],
            'classes' => [
                'Mage_Core_Helper_Abstract' => 'Magento_Framework_App_Helper_AbstractHelper',
                'Mage_Core_Helper_Data' => 'Magento_Framework_App_Helper_AbstractHelper',
                'Mage_Core_Helper_' => 'Magento_Framework_App_Helper_',
                'Mage_Core_Model_Abstract' => 'Magento_Framework_Model_AbstractModel',
                'Mage_Core_Model_Mysql4_Abstract' => 'Magento_Framework_Model_Resource_Db_AbstractDb',
                'Mage_Core_Model_Mysql4_Collection_Abstract' => 'Magento_Framework_Model_ResourceModel_Db_Collection_AbstractCollection',
                'Mage_Core_Model_Resource_Setup' => 'Magento_Framework_Module_Setup',
                'Mage_Core_Model_Url_Rewrite' => 'Magento_UrlRewrite_Model_UrlRewrite',
                'Mage_Core_Model_Config_Data' => 'Magento_Framework_App_Config_Value',
                'Mage_Core_Model_Mysql4_Config_' => 'Magento_Config_Model_ResourceModel_Config_',
                'Mage_Core_Model_Resource_Config_' => 'Magento_Config_Model_ResourceModel_Config_',
                'Mage_Core_Block_Abstract' => 'Magento_Framework_View_Element_AbstractBlock',
                'Mage_Core_Block_Template' => 'Magento_Framework_View_Element_Template',
                'Mage_Core_Controller_Front_Action' => 'Magento_Framework_App_Action_Action',
                'Mage_Core_' => 'Magento_Framework_',
                'Mage_Adminhtml_Controller_Action' => 'Magento_Backend_App_Action',
                #'Mage_Adminhtml_Block_Widget_Grid' => 'Magento_Backend_Block_Widget_Grid_Extended',
                'Mage_Adminhtml_Block_Catalog_' => 'Magento_Catalog_Block_Adminhtml_',
                'Mage_Adminhtml_Block_Customer_' => 'Magento_Customer_Block_Adminhtml_',
                'Mage_Adminhtml_Block_Sales_' => 'Magento_Sales_Block_Adminhtml_',
                'Mage_Adminhtml_Block_Messages' => 'Magento_Framework_View_Element_Messages',
                'Mage_Adminhtml_Block_Report_Filter_Form' => 'Magento_Reports_Block_Adminhtml_Filter_Form',
                'Mage_Adminhtml_Block_System_Config_Form_Field_Array_Abstract' => 'Magento_Config_Block_System_Config_Form_Field_FieldArray_AbstractFieldArray',
                'Mage_Adminhtml_Block_Text_List' => 'Magento_Backend_Block_Text_ListText',
                'Mage_Adminhtml_Block_System_Config_' => 'Magento_Config_Block_System_Config_',
                'Mage_Adminhtml_Block_System_Variable' => 'Magento_Variable_Block_System_Variable',
                'Mage_Adminhtml_Block_Checkout_Agreement_' => 'Magento_CheckoutAgreements_Block_Adminhtml_Agreement_',
                'Mage_Adminhtml_Model_System_Config_Source_Country' => 'Magento_Directory_Model_Config_Source_Country',
                'Mage_Adminhtml_Model_System_Config_Source_Allregion' => 'Magento_Directory_Model_Config_Source_Allregion',
                'Mage_Adminhtml_Model_System_Config_Source_' => 'Magento_Config_Model_Config_Source_',
                'Mage_Adminhtml_Model_System_Store' => 'Magento_Store_Model_System_Store',
                'Mage_Adminhtml_Controller_System_Config_System_Storage' => 'Magento_Config_Controller_Adminhtml_System_Config_System_Storage',
                'Mage_Adminhtml_Controller_Checkout_Agreement' => 'Magento_Checkout_Controller_Adminhtml_Agreement',
                'Mage_Adminhtml_' => 'Magento_Backend_',
                'Mage_Admin_Model_Acl' => 'Magento_Framework_Acl',
                'Mage_Admin_Model_Roles' => 'Magento_Authorization_Model_Role',
                'Mage_Admin_Model_Resource_Roles_Collection' => 'Magento_Authorization_Model_ResourceModel_Role_Collection',
                'Mage_Admin_' => 'Magento_Backend_',
                'Mage_MediaStorage_Controller_System_Config_System_Storage' => 'Magento_MediaStorage_Controller_Adminhtml_System_Config_System_Storage',
                'Mage_Page_Model_Source_Layout' => 'Magento_Cms_Model_Page_Source_PageLayout',
                'Mage_Page_' => 'Magento_Framework_',
                'Mage_Rule_Model_Rule' => 'Magento_Rule_Model_AbstractModel',
                'Mage_Usa_Block_Adminhtml_Dhl_' => 'Magento_Dhl_Block_Adminhtml_',
                'Mage_Usa_Model_Shipping_Carrier_Dhl_Abstract' => 'Magento_Dhl_Model_AbstractDhl',
                'Mage_Usa_Model_Shipping_Carrier_Dhl_International_' => 'Magento_Dhl_Model_',
                'Mage_Usa_Model_Shipping_Carrier_Dhl_International' => 'Magento_Dhl_Model_Carrier',
                'Mage_Usa_Model_Simplexml_Element' => 'Magento_Shipping_Model_Simplexml_Element',
                'Mage_Usa_Model_Shipping_Carrier_AbstractCarrier' => 'Magento_Shipping_Model_Carrier_AbstractCarrierOnline',
                'Mage_Usa_Model_Shipping_Carrier_AbstractCarrier_Source_Mode' => 'Magento_Shipping_Model_Config_Source_Online_Mode',
                'Mage_Usa_Model_Shipping_Carrier_AbstractCarrier_Source_Requesttype' => 'Magento_Shipping_Model_Config_Source_Online_Requesttype',
                'Mage_Index_' => 'Magento_Indexer_',
                'Mage_' => 'Magento_',
                'Varien_Io_' => 'Magento_Framework_Filesystem_Io_',
                'Varien_Object' => 'Magento_Framework_DataObject',
                'Varien_' => 'Magento_Framework_',
                '_Model_Mysql4_' => '_Model_ResourceModel_',
                '_Model_Resource_' => '_Model_ResourceModel_',
                '_Model_ResourceModel_Abstract' => '_Model_ResourceModel_AbstractResource',
                'Zend_Json' => 'Zend_Json_Json',
                'Zend_Log' => 'Zend_Log_Logger',
                'Zend_Db' => 'Magento_Framework_Db',
            ],
            'classes_regex' => [
                '#_([A-Za-z0-9]+)_(Abstract|New|List)([^A-Za-z0-9_]|$)#' => '_\1_\2\1\3',
                '#_([A-Za-z0-9]+)_(Interface)([^A-Za-z0-9_]|$)#' => '_\1_\1\2\3',
                '#_Protected(?![A-Za-z0-9_])#' => '_ProtectedCode',
                #'#(Mage_[A-Za-z0-9_]+)_Grid([^A_Za-z0-9_])#' => '\1\2',
                '#Magento_Backend_Block_(Catalog)_#' => 'Magento_\2_Block_Adminhtml_',
                '#Magento_Backend_(Block|Controller)_Promo_Quote#' => 'Magento_SalesRule_\1_Adminhtml_Promo_Quote',
                '#Magento_Backend_(Block|Controller)_Promo_(Catalog|Widget)#' => 'Magento_CatalogRule_\1_Adminhtml_Promo_\2',
                '#Magento_Usa_Model_Shipping_Carrier_(Fedex|Ups|Usps)_#' => 'Magento_\1_Model_',
                '#Magento_Usa_Model_Shipping_Carrier_(Fedex|Ups|Usps)#' => 'Magento_\1_Model_Carrier',
                '#([^A-Za-z0-9_]|^)([A-Za-z0-9]+_[A-Za-z0-9]+_Controller_)([A-Za-z0-9_]+_)?([A-Za-z0-9]+)Controller([^A-Za-z0-9_]|$)#' => '\1\2\3\4_Abstract\4\5',
                '#([^A-Za-z0-9_]|^)([A-Za-z0-9]+_[A-Za-z0-9var]+_)([A-Za-z0-9_]+_)?([A-Za-z0-9]+)Controller([^A-Za-z0-9_]|$)#' => '\1\2Controller_\3\4_Abstract\4\5',
            ],
            'code' => [
                'Mage_Core_Model_Locale::DEFAULT_LOCALE' => '\Magento\Framework\Locale\Resolver::DEFAULT_LOCALE',
                'Mage_Core_Model_Translate::CACHE_TAG' => '\Magento\Framework\App\Cache\Type::CACHE_TAG',

                'Mage::log(' => $this->_objMgr . '(\'Psr\Log\LoggerInterface\')->log(',
                'Mage::logException(' => $this->_objMgr . '(\'Psr\Log\LoggerInterface\')->error(',
                'Mage::dispatchEvent(' => $this->_objMgr . '(\'Magento\Framework\Event\ManagerInterface\')->dispatch(',
                'Mage::app()->getRequest()' => $this->_objMgr . '(\'Magento\Framework\App\RequestInterface\')',
                'Mage::app()->getLocale()->getLocaleCode()' => $this->_objMgr . '(\'Magento\Framework\Locale\Resolver\')->getLocale()',
                'Mage::app()->getStore(' => $this->_objMgr . '(\'Magento\Store\Model\StoreManagerInterface\')->getStore(',
                'Mage::app()->getCacheInstance()->canUse(' => $this->_objMgr . '(\'Magento\Framework\App\Cache\StateInterface\')->isEnabled(',
                'Mage::app()->getCacheInstance()' => $this->_objMgr . '(\'Magento\Framework\App\CacheInterface\')',
                'Mage::getConfig()->getModuleDir(' => $this->_objMgr . '(\'Magento\Framework\Module\Dir\Reader\')->getModuleDir(',
                'Mage::getConfig()->getVarDir(' => $this->_objMgr . '(\'Magento\Framework\App\Filesystem\DirectoryList\')->getPath(\'var\') . (',
                'Mage::getConfig()->createDirIfNotExists(' => $this->_objMgr . '(\'Magento\Framework\Filesystem\Directory\Write\')->create(',
                'Mage::getStoreConfig(' => $this->_objMgr . '(\'Magento\Framework\App\Config\ScopeConfigInterface\')->getValue(',
                'Mage::getStoreConfigFlag(' => $this->_objMgr . '(\'Magento\Framework\App\Config\ScopeConfigInterface\')->isSetFlag(',
                'Mage::getDesign()' => $this->_objMgr . '(\'Magento\Framework\View\DesignInterface\')',
                'Mage::helper(\'core/url\')->getCurrentUrl()' => $this->_objMgr . '(\'Magento\Framework\UrlInterface\')->getCurrentUrl()',
                'Mage::getBaseUrl(' => $this->_objMgr . '(\'Magento\Framework\UrlInterface\')->getBaseUrl(',
                'Mage::getBaseDir(' => $this->_objMgr . '(\'Magento\Framework\Filesystem\')->getDirPath(',
                'Mage::getSingleton(\'admin/session\')->isAllowed(' => $this->_objMgr . '(\'Magento\Backend\Model\Auth\Session\')->isAllowed(',
                'Mage::getSingleton(\'adminhtml/session\')->add' => $this->_objMgr . '(\'Magento\Framework\Message\ManagerInterface\')->add',
                'Mage::throwException(' => 'throw new Exception(',
                ' extends Exception' => ' extends \Exception',
                '$this->getResponse()->setBody(' => $this->_objMgr . '(\'Magento\Framework\Controller\Result\RawFactory\')->create()->setContents(',
                '$this->getLayout()' => $this->_objMgr . '(\'Magento\Framework\View\LayoutFactory\')->create()',
                '$this->_redirect(' => $this->_objMgr . '(\'Magento\Framework\Controller\Result\RedirectFactory\')->create()->setPath(',
                '$this->_forward(' => $this->_objMgr . '(\'Magento\Backend\Model\View\Result\ForwardFactory\')->create()->forward(',
                //TODO: Need help with:
                #'Mage::app()->getConfig()->getNode(' => '',
            ],
            'code_regex' => [
                '#(Mage::helper\([\'"][A-Za-z0-9/_]+[\'"]\)|\$this)->__\(#' => '__(',
                '#Mage::(registry|register|unregister)\(#' => $this->_objMgr . '(\'Magento\Framework\Registry\')->\1(',
                '#Mage::helper\(\'core\'\)->(encrypt|decrypt|getHash|hash|validateHash)\(#' => $this->_objMgr . '(\'Magento\Framework\Encryption\Encryptor\')->\1(',
                '#Mage::getConfig\(\)->getNode\(([\'"][^)]+[\'"])\)#' => $this->_objMgr . '(\'Magento\Framework\App\Config\ScopeConfigInterface\')->getValue(\1\2\3, \'default\')',
                '#Zend_Validate::is\(([^,]+),\s*[\'"]([A-Za-z0-9]+)[\'"]\)#' => '(new \Zend\Validator\\\\\2())->isValid(\1)',
            ],
            'acl_keys' => [
                'admin' => 'Magento_Backend::admin',
                'admin/sales' => 'Magento_Sales::sales',
                'admin/reports' => 'Magento_Reports::report',
                'admin/system' => 'Magento_Backend::stores',
                'admin/system/config' => ['Magento_Backend::stores_settings', 'Magento_Config::config'],
            ],
            'menu' => [
                'sales' => 'Magento_Sales::sales',
                'report' => 'Magento_Reports:report',
            ],
            'files_regex' => [
                '#/Model/(Mysql4|Resource)/#' => '/Model/ResourceModel/',
                '#/Model/ResourceModel/Abstract#' => '/Model/ResourceModel/AbstractResource',
                '#/Protected\.php#' => '/ProtectedCode.php',
                '#/([A-Za-z0-9]+)/(Abstract|New|List)([^A-Za-z0-9/]|$)#' => '/\1/\2\1\3',
                '#/([A-Za-z0-9]+)/(Interface)([^A-Za-z0-9/]|$)#' => '/\1/\1\2\3',
            ],
        ];
    }
}